.\"                                      Hey, EMACS: -*- nroff -*-
.TH MUNIN-VALA-PLUGINS 1 "January  05, 2012"
.SH NAME
munin-vala-plugins \- speed up your munin plugins
.SH SYNOPSIS
.SY munin-vala-plugins
.OP OPTIONS
.SH DESCRIPTION
\fB
.SH OPTIONS
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
.SS "Application Options:"
.SH AUTHOR
munin-vala-plugins was written by Thomas Ludwig <moonmaker@gmx.de>.
.PP
This manual page was written by Thomas Ludwig <moonmaker@gmx.de>,
for the Debian and Ubuntu project (and may be used by others).
